"use client";

import { Download, ExternalLink, Printer } from "lucide-react";
import { buildMemoSources } from "@/lib/memo";
import type { AICommitteeRun, Evidence, SearchRun } from "@/lib/types";

function Ref({ number }: { number?: number }) {
  return number ? <a className="memo-ref" href={`#memo-source-${number}`} aria-label={`Source ${number}`}>[{number}]</a> : null;
}

export function InvestmentMemo({ run, ai }: { run: SearchRun; ai: AICommitteeRun | null }) {
  const refs = buildMemoSources(run, ai);
  const evidence = new Map(run.evidence.map(item => [item.id, item]));
  const cited = (ids: string[]) => [...new Set(ids.map(id => refs.evidenceNumbers[id]).filter((value): value is number => !!value))].map(number => <Ref key={number} number={number} />);
  const published = (id: string) => (evidence.get(id) as Evidence | undefined)?.publishedAt;
  const urlRef = (url: string) => <Ref number={refs.urlNumbers[url]} />;

  function downloadReport() {
    const sheet = document.querySelector(".memo-sheet");
    if (!sheet) return;
    const style = `@page{size:A4;margin:16mm}body{font:14px/1.6 Arial,sans-serif;color:#243650;margin:0;background:#f5f7fb}.memo-sheet{max-width:820px;margin:24px auto;padding:48px;background:#fff}.memo-cover{border-bottom:2px solid #3159dd;padding-bottom:20px}.memo-kicker{font-size:11px;color:#5270c3;letter-spacing:1px;font-weight:bold}.memo-cover h2{font-size:32px;margin:12px 0 0}.memo-cover p,.memo-meta{color:#697b96}.memo-meta,.memo-status{font-size:12px}.memo-alert{background:#f1f5ff;border-left:3px solid #3159dd;padding:14px;margin:20px 0}.memo-alert strong{display:block}.memo-section{border-top:1px solid #e3e9f2;padding:20px 0}.memo-section h3{margin:0 0 10px}.memo-entry,.memo-source{border-top:1px solid #edf1f7;padding:10px 0}.memo-entry h4{margin:0 0 5px}.memo-entry p,.memo-section p{margin:6px 0}.memo-ref{color:#3159dd;margin-left:4px}.memo-source strong,.memo-source span,.memo-source a{display:block}.memo-source span{font-size:11px;text-transform:uppercase;color:#8492a9}.memo-source a{overflow-wrap:anywhere;color:#3159dd;font-size:12px}.memo-source svg{display:none}@media print{body{background:#fff}.memo-sheet{margin:0;padding:0}.memo-section,.memo-entry,.memo-source{break-inside:avoid}}`;
    const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ThesisOS investment memo</title><style>${style}</style></head><body>${sheet.outerHTML}</body></html>`;
    const url = URL.createObjectURL(new Blob([html], { type: "text/html;charset=utf-8" }));
    const link = document.createElement("a");
    link.href = url;
    link.download = `thesisos-${run.thesis.sector.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "memo"}.html`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.setTimeout(() => URL.revokeObjectURL(url), 1000);
  }

  return <div className="memo-view">
    <div className="memo-toolbar"><div><span className="small-overline">DECISION ARTIFACT</span><h3>Investment thesis memo</h3><p>Save a standalone copy or print it as a PDF.</p></div><div className="memo-actions"><button className="memo-download-button" onClick={downloadReport}><Download size={15} /> Download report</button><button className="ai-button" onClick={() => window.print()}><Printer size={15} /> Print / save PDF</button></div></div>
    <article className="memo-sheet">
      <header className="memo-cover"><span className="memo-kicker">THESISOS · INVESTMENT INTELLIGENCE</span><h2>{run.thesis.sector}</h2><p>{run.thesis.geography} · {run.thesis.stage}</p><div className="memo-meta">Research run: {new Date(run.searchedAt).toLocaleString()} · {run.queries.filter(item => item.ok).length}/{run.queries.length} live queries completed</div></header>
      <div className="memo-alert"><strong>Research brief, not an investment recommendation.</strong> Search previews, AI output, public job listings, papers, and patents require direct verification. Private company financials and customer traction remain unavailable unless explicitly cited.</div>
      {run.thesis.thesis && <section className="memo-section"><h3>Investment question</h3><p>{run.thesis.thesis}</p></section>}
      <section className="memo-section"><h3>Executive assessment</h3><p>{run.committee?.chair || "No rule-based assessment available."}</p><p><strong>Evidence readiness:</strong> {run.committee?.readinessScore ?? "unavailable"}/100. This measures public research coverage, not investment attractiveness.</p>{run.warnings.length > 0 && <p><strong>Incomplete searches:</strong> {run.warnings.join(" · ")}</p>}</section>
      <section className="memo-section"><h3>Startup candidates</h3>{run.startups.length ? run.startups.map(item => <div className="memo-entry" key={item.id}><h4>{item.name} <span className="memo-status">{item.nameStatus}</span> <Ref number={refs.evidenceNumbers[item.evidenceIds[0]]} /></h4><p><strong>Geography:</strong> {item.geography} ({item.geographyStatus}) <Ref number={item.geographyEvidenceId ? refs.evidenceNumbers[item.geographyEvidenceId] : undefined} /> · <strong>Stage:</strong> {item.stageStatus === "unavailable" ? "unavailable" : item.stage} ({item.stageStatus}) <Ref number={item.stageEvidenceId ? refs.evidenceNumbers[item.stageEvidenceId] : undefined} /> · <strong>Funding:</strong> {item.fundingStatus === "unavailable" ? "unavailable" : item.funding} ({item.fundingStatus}) <Ref number={item.fundingEvidenceId ? refs.evidenceNumbers[item.fundingEvidenceId] : undefined} /></p><p><strong>Search preview:</strong> {item.description}</p></div>) : <p>No candidate names passed the current extraction rules.</p>}</section>
      <section className="memo-section"><h3>Key developments</h3>{run.developments.length ? run.developments.map(item => <div className="memo-entry" key={item.id}><h4>{item.title} {cited(item.evidenceIds.slice(0, 3))}{item.evidenceIds.length > 3 && <span className="memo-status"> +{item.evidenceIds.length - 3} sources in register</span>}</h4><p>{item.category} · {item.status} · {item.evidenceIds.length} reporting source{item.evidenceIds.length === 1 ? "" : "s"}{published(item.evidenceId) ? ` · ${published(item.evidenceId)}` : ""}</p><p>{item.summary}</p></div>) : <p>No relevant recent news item was found.</p>}</section>
      <section className="memo-section"><h3>Risks to investigate</h3>{run.risks.length ? run.risks.map(item => <div className="memo-entry" key={item.id}><h4>Source headline: {item.title} <Ref number={refs.evidenceNumbers[item.evidenceId]} /></h4><p><strong>Possible market effect ({item.status}):</strong> {item.marketEffect}</p><p><strong>Thesis implication ({item.status}):</strong> {item.thesisImplication}</p></div>) : <p>No explicit risk headline passed the filter. This does not imply low risk.</p>}</section>
      <section className="memo-section"><h3>Additional signals</h3>{run.signals.trend ? <p><strong>Search interest:</strong> Recent 13-week relative average {run.signals.trend.recentAverage}/100 versus {run.signals.trend.previousAverage}/100 in the prior 13 weeks. This is not a demand estimate. {urlRef(run.signals.trend.url)}</p> : <p><strong>Search interest:</strong> unavailable.</p>}<p><strong>Hiring:</strong> {run.signals.jobs.length} topic-matched public listings. A listing does not prove growth.</p>{run.signals.jobs.map(item => <p className="memo-small-line" key={item.url}>{item.company} · {item.title} · {item.location} {urlRef(item.url)}</p>)}</section>
      <section className="memo-section"><h3>Research and patent landscape</h3><p>Publications and patents help identify prior work. They do not establish company ownership, enforceable protection, or freedom to operate.</p><h4>Publications</h4>{run.signals.papers.length ? run.signals.papers.map(item => <p className="memo-small-line" key={item.url}>{item.title} · {item.detail} {urlRef(item.url)}</p>) : <p>No topic-matched publication returned.</p>}<h4>Patents</h4>{run.signals.patents.length ? run.signals.patents.map(item => <p className="memo-small-line" key={item.url}>{item.title} · {item.detail} {urlRef(item.url)}</p>) : <p>No topic-matched patent returned.</p>}</section>
      <section className="memo-section"><h3>Committee questions for diligence</h3>{run.committee?.voices.map(voice => <div className="memo-entry" key={voice.role}><h4>{voice.role} {cited(voice.evidenceIds)}</h4><p>{voice.observation}</p><p><strong>Ask:</strong> {voice.nextQuestion}</p></div>)}</section>
      {ai && <section className="memo-section"><h3>Google AI Mode committee · unverified</h3><p>Generated text below is a second opinion. Its references are supplied by AI Mode and may not support every claim. Verify them before use.</p>{ai.voices.map(voice => <div className="memo-entry" key={voice.role}><h4>{voice.role}</h4><p>{voice.summary} {voice.summaryCitations.length ? voice.summaryCitations.map(source => <Ref key={source.url} number={refs.urlNumbers[source.url]} />) : <span className="memo-status">Uncited AI claim</span>}</p>{voice.points.map((point, index) => <p key={index}>{point.text} {point.citations.length ? point.citations.map(source => <Ref key={source.url} number={refs.urlNumbers[source.url]} />) : <span className="memo-status">Uncited AI claim</span>}</p>)}</div>)}{ai.chair && <div className="memo-entry"><h4>Committee chair</h4><p>{ai.chair.summary} {ai.chair.summaryCitations.length ? ai.chair.summaryCitations.map(source => <Ref key={source.url} number={refs.urlNumbers[source.url]} />) : <span className="memo-status">Uncited AI synthesis</span>}</p>{ai.chair.points.map((point, index) => <p key={index}>{point.text} {point.citations.length ? point.citations.map(source => <Ref key={source.url} number={refs.urlNumbers[source.url]} />) : <span className="memo-status">Uncited AI claim</span>}</p>)}</div>}</section>}
      <section className="memo-section memo-sources"><h3>Source register</h3>{refs.sources.map(source => <div className="memo-source" id={`memo-source-${source.number}`} key={source.number}><strong>[{source.number}] {source.title}</strong><span>{source.kind}</span><a href={source.url} target="_blank" rel="noopener noreferrer">{source.url} <ExternalLink size={11} /></a></div>)}</section>
    </article>
  </div>;
}
